
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="LGPLv3"

[[mods]] #mandatory

modId="experienced_crops" #mandatory

version = "${version}"

displayName="Experienced Crops" #mandatory

logoFile="icon.png" #optional

authors="Ordana" #optional

description='''
Obtain xp orbs from fully grown crops!
'''

[[dependencies.experienced_crops]] #optional
    # the modid of the dependency
    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[40,)" #mandatory

    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.experienced_crops]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.experienced_crops]]

    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.0.35,]"
    ordering="AFTER"
    side="BOTH"
